spring:
  datasource:
    url: jdbc:mysql://localhost:3306/certificate_security_db
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
